/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class secondlab_SecondLab */

#ifndef _Included_secondlab_SecondLab
#define _Included_secondlab_SecondLab
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     secondlab_SecondLab
 * Method:    process
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_secondlab_SecondLab_process
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
